######################################
### Configure programming language ###
######################################
language: java

##################################
### Make sure using Oracle JDK ###
##################################
jdk:
  - oraclejdk13

###################################
### Disable Email notifications ###
###################################
notifications:
  email: false

###############
### Caching ###
###############
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

#################
### SonarQube ###
#################
addons:
  sonarcloud:
    organization: "mysteryworlds"
    token:
      secure: I+rF0aI7GoLV6AOAJfFrMR+QbEfIpm2vE2WpNTJOMIR+lT12K6PwjOLJ7x7wn839Qu/YLIj1FnVbxOAEgebjAtpvoREBJ6MeO/ZqDkUr3597a4E78wVE15YY0x8J634FgHu9chYJBfgzlSupMppl6uS+bxgw8/AV2T/9LsPoSwAiGzv0UVv1xWOqVtGjeFvFiwlB6oh/qqYaw64hHfSid+Fk9n5d5PAJMItludmv0dOlbFXPrS6C+lkyXpwaaEOSUmV29JkDRL74moorSb/W9sQjwTdjG1F8DH376qAUIS9Iz8lV7uQ2t+KwkaLvfsCVvOvPLNIyln8bEzjfYdtnJu0icihz+93m1iqMH7Xg21zt2yYkCqNGxYMX4r8wrttWBx8+hn2kQpQH0jgjZH80GcIjXL992ea5sUUoEUbWVyPn6shvRwEWQTVoUk7qWAyh4Y0DFAYlBAXDybWII1DKpzBz6k3vgNDpU3Mxd1IFF561EHxrp4NjnDYpFC8ZKEikJE+8ZMVr3kYwtPa/jJzToPykZZn3Dt/04oHMxCObnagoRpyTF3G2FdLqvPnF7Z2NfjoZ52M/x1n9Rm/xy55UOpC15qb3I8YcYMtbedCN8SkFFWuKdcZEKXOwc1c7crACyUg1qVb60MjF+dM0ozigVCeRH2GuBAk9VxqZMkcLri8=

###########################
### Actual Build Script ###
###########################
script:
  - ./gradlew build
  - ./gradlew check
  - ./gradlew codeCoverageReport
  - ./gradlew --scan -s
  - ./gradlew sonarqube

##################
### Deployment ###
##################
deploy:
  provider: script
  script: ./gradlew publish
  on:
    tags: true